CREATE TABLE user_account
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,

    is_enabled    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    is_non_locked BOOLEAN                                 NOT NULL DEFAULT TRUE,
    is_using2fa   BOOLEAN                                 NOT NULL DEFAULT FALSE,

    secret        VARCHAR(255),

    user_id       BIGINT                                  NOT NULL,
    role_id       BIGINT,

    CONSTRAINT pk_user_account PRIMARY KEY (id),
    CONSTRAINT uc_user_account_user UNIQUE (user_id),
    CONSTRAINT uk_user_account_username UNIQUE (username),
    CONSTRAINT fk_user_account_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_user_account_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_user_account_role_id ON user_account(role_id);