ALTER TABLE users
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS bio VARCHAR(1000);
