ALTER TABLE users DROP COLUMN IF EXISTS username;
ALTER TABLE users DROP COLUMN IF EXISTS nickname;
ALTER TABLE users DROP COLUMN IF EXISTS password;
ALTER TABLE users DROP COLUMN IF EXISTS is_enabled;
ALTER TABLE users DROP COLUMN IF EXISTS is_non_locked;
ALTER TABLE users DROP COLUMN IF EXISTS is_using2fa;
ALTER TABLE users DROP COLUMN IF EXISTS secret;
ALTER TABLE users DROP COLUMN IF EXISTS role_id;
