GET localhost:8080/api/recipeEntity/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYXJ0ZWttYXJrMDBAZ21haWwuY29tIiwiaWF0IjoxNzcwMDY1MDY3LCJleHAiOjE3NzAwNzk0Njd9.u2FnXdRDtF0H6pzpPWxDdvDGXvbFB1_rP8yhz03qqKg

###