POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json

{
  "email": "bartekmark00@gmail.com",
  "password": "test12345"
}

###

GET http://localhost:8080/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYXJ0ZWttYXJrMDBAZ21haWwuY29tIiwiaWF0IjoxNzU5MTcxNDg3LCJleHAiOjE3NTkxODU4ODd9.aSwpe1uC9IyGvfPVEqqJlKwgJzdDLcfd0K8IubmBP9s
